ALTER TABLE expenses ADD COLUMN IF NOT EXISTS original_currency TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS original_amount BIGINT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS exchange_rate DOUBLE PRECISION;
